'use strict';

exports.SEMICOLON_SEPARATOR = ';';
exports.PIPE_SEPARATOR = '|';
exports.COLON_SEPARATOR = ':';
exports.ANGLE_SEPARATOR = '>';
exports.GOOGLE_CATEGORY_PATH = 'Apparel & Accessories > Jewelry > ';
exports.YEAR_MONTH_DATE_PATTERN = 'yyyy-MM-dd';
exports.CURRENCY_USD = 'USD';
exports.CURRENCY_GBP = 'GBP';
exports.CURRENCY_CAD = 'CAD';
exports.CURRENCY_EUR = 'EUR';
exports.CURRENCY_AUD = 'AUD';
exports.CURRENCY_MXN = 'MXN';
exports.CURRENCY_SGD = 'SGD';
exports.CURRENCY_MYR = 'MYR';
exports.CURRENCY_HKD = 'HKD';
exports.CURRENCY_CHF = 'CHF';
exports.COUNTRY_US = 'US';
exports.COUNTRY_GB = 'GB';
exports.COUNTRY_CA = 'CA';
exports.COUNTRY_BE = 'BE';
exports.COUNTRY_AU = 'AU';
exports.COUNTRY_FR = 'FR';
exports.HOUR_MINUTE_SECOND_PATTERN = 'HH:mm-ss';
exports.DATE_TIME_SEPERATOR = 'T';
exports.PROMOTION_START_END_DATE_SEPARATOR = '/';