'use strict';

exports.KLARNA_PAYMENT_METHOD_TEXT = 'klarna';
exports.PAYMENT_STATUS_AUTHORISED = 'AUTHORISED';
exports.PAYMENT_STATUS_CAPTURE = 'CAPTURE';
exports.PAYMENT_STATUS_CANCELLED = 'CANCELLED';