'use strict';

exports.BACK_IN_STOCK_NOTIFICATION_OBJECT = 'BackInStockNotification';
exports.FILE_NAME_AND_DATE_TIME_SEPARATOR = '-';
exports.DATE_TIME_FORMAT = "MM/dd/yyyy";
exports.FILE_DATE_TIME_FORMAT = "MM-dd-yyyy-h-mm-a";
exports.PRODUCT_IMAGE_PLACEHOLDER = "<PRODUCT_IMAGE_PLACEHOLDER>";
exports.PRODUCT_URL_PLACEHOLDER = "<PRODUCT_URL_PLACEHOLDER>";
exports.OUTLOOK_PRODUCT_URL_PLACEHOLDER = "<OUTLOOK_PRODUCT_URL_PLACEHOLDER>";
exports.PROMOTION_START_END_DATE_SEPARATOR = '/';
exports.PRICE_LOW_TO_HIGH = 'price-low-to-high';
exports.PRICE_HIGH_TO_LOW = 'price-high-to-low';
exports.ROOT_CATEGORY = 'root';
exports.YOTPO_REFINEMENT_ID = 'yotpoAverageScore';
exports.EN_LOCALE = 'en';
exports.EN_GB_LOCALE = 'en_GB';
exports.WATCH_INITIALS = 'OB16';
exports.WATCHES_INITIALS = '240';
exports.STRAPS_INITIALS = '243';
exports.JEWELRY_INITIALS = '241';
exports.JEWELRY_INITIALS_CHAR = 'OBJ';
exports.WATCHES_CATEGORY= 'watches';
exports.JEWELRY_CATEGORY= 'jewelry';
exports.SMALL_MM_UNIT= 'mm';
