'use strict';

exports.BACK_IN_STOCK_NOTIFICATION_OBJECT = 'BackInStockNotification';
exports.FILE_NAME_AND_DATE_TIME_SEPARATOR = '-';
exports.DATE_TIME_FORMAT = "MM/dd/yyyy";
exports.FILE_DATE_TIME_FORMAT = "MM-dd-yyyy-h-mm-a";
exports.PRODUCT_IMAGE_PLACEHOLDER = "<PRODUCT_IMAGE_PLACEHOLDER>";
exports.PRODUCT_URL_PLACEHOLDER = "<PRODUCT_URL_PLACEHOLDER>";
exports.OUTLOOK_PRODUCT_URL_PLACEHOLDER = "<OUTLOOK_PRODUCT_URL_PLACEHOLDER>";
exports.PROMOTION_START_END_DATE_SEPARATOR = '/';