'use strict';

exports.DEFAULT_COUNTRYCODE = 'US';
exports.NOT_AVAILABILITY_STATUS = 'NOT_AVAILABLE';
exports.FAMILY_NAME_AND_CASE_DIAMETER_SEPARATOR = ' - ';
exports.MM_UNIT='MM';
exports.MVMT_CHECKOUT_CAMPAIGN_NAME='Checkout2';