'use strict';

exports.DEFAULT_COUNTRYCODE = 'US';
exports.NOT_AVAILABILITY_STATUS = 'NOT_AVAILABLE';
exports.FAMILY_NAME_AND_CASE_DIAMETER_SEPARATOR = ' - ';
exports.MM_UNIT='MM';
exports.MM_UNIT_SMALL='mm';
exports.MVMT_CHECKOUT_CAMPAIGN_NAME='Checkout';
exports.WATCHES_CATEGORY='watches';
exports.JEWELRY_CATEGORY='jewelry';
exports.EYEWEAR_CATEGORY='eyewear';
exports.STRAPS_CATEGORY='strapguide';
exports.US_COUNTRY_CODE='US';
exports.DE_COUNTRY_CODE='DE';
exports.RAKUTEN_COOKIE_NAME='rmStoreGateway';
exports.DATE_FORMAT='E, dd MMM yyyy HH:mm:ss z';
exports.ALD_DATE_FORMAT='YYYYMMdd_HHMM';
exports.ONE_TRUST_COOKIE_ENABLED = 'C0004:1';
exports.OPTANON_CONSENT_COOKIE_NAME = 'OptanonConsent';
exports.FAMILY_NAME_AND_CASE_DIAMETER_SEPARATOR_REDESIGN = ' | ';
